### ISSUE TITLE
scipy and pandas install were required as well

### ISSUE THREAD

**Issue by laripernu** [ahmetyavuzd/SPAN#3]
Taking the plugin into test, I noticed a requirement for pip installing also `scipy` and `pandas` in addition to the README-listed dependencies. Would it be useful to add these into to the instructions? Thank you for making the plugin!

**Comment by ahmetyavuzd** [comment]
Thank you for your feedback. This suggestion was a very important contribution to the plugin. It will be added to the readme file as soon as possible.
